### PR TITLE
Indicate types file location

### PR DESCRIPTION
**Pull request by zhangciwu**
Doc: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

### CODE REVIEW

**Comment by loilo** [comment]
Nice one, didn't know that.

Do you know when this is necessary (i.e. when TypeScript will *not* just look up the JS file name with the `.d.ts` extension)?

**Comment by zhangciwu** [comment]
My webstorm would be unable to jump to typedefs without this indication.
I added manually and then it can jump to `d.ts`

And in the doc:
```
Also note that if your main declaration file is named index.d.ts and lives at the root of the package (next to index.js) you do not need to mark the "types" property, though it is advisable to do so.

```
So for `index.d.ts` in sub forders, `types` field would be required for tools to resolve type file location

**Comment by loilo** [comment]
Alright then, thanks for the valuable addition. 🙂

**Comment by loilo** [comment]
This change has just been released with v2.0.9. 🥳

Thanks again for contributing! 🙂

**Pull request merged**
